### ISSUE TITLE
bower support

### ISSUE THREAD

**Issue by fredericgrati** [avocode/combokeys#23]
Should be great to have a bower.json in order to support the bower package management.

**Comment by mightyiam** [comment]
Is there a way to add bower support without checking in a build?

**Comment by FuDesign2008** [comment]
+1

**Comment by petrbrzek** [comment]
We don't want to support Bower (https://medium.com/@basarat/friends-don-t-let-friends-use-bower-380bba84111a#.qh7jpw7a2).
