### ISSUE TITLE
Repo maintenance

### ISSUE THREAD

**Issue by robincafolla** [avocode/combokeys#45]
Hi there, I've recently [forked mousetrap](https://github.com/mousetrap-js/mousetrap) to close bugs and merge pull requests, not having realised you've already done so.

Is anyone still actively maintaining this repo? I don't want to waste time and effort fixing already fixed bugs.

**Comment by winhamwr** [comment]
Hello Robin,

We use this as a dependency, but we're no longer actively working on it. If you're interested in doing maintenance, we'd be very happy to give you full access to this repo, or transfer it to an organization of your choosing. Whichever you'd prefer.

Thanks
-Wes

**Comment by petrbrzek** [comment]
Hello @winhamwr , we use combokeys in react-shortcuts (https://github.com/avocode/react-shortcuts). I think we could do some maintenance if needed under Avocode organization. Would it be possible to discuss the transfer?

**Comment by winhamwr** [comment]
Hi Petr,

If you're actively using it, then the highest-value location for the code is where you'll be most likely to maintain it. I'm absolutely interested in that.

Do you know the steps required to do the transfer? A [quick search](https://help.github.com/articles/transferring-a-repository-owned-by-your-organization/) seems to suggest that the person doing the transfer must have "admin" permissions for both organizations. If that's the case, if you could give me temporary admin, I would be happy to make the transfer and then you could revoke that permission. 

Is there another way to do that?

Thanks
-Wes

**Comment by petrbrzek** [comment]
Hi Wes, yeah I think it's as you wrote. We only have public repositiories under our account so I have no problem to give you temporary admin access. When would you have time for it?  Thanks.

**Comment by winhamwr** [comment]
Hi Petr,

I can definitely do it, today.

-Wes

**Comment by petrbrzek** [comment]
@winhamwr I'm adding you as an admin and will revoke the access on Monday at 9 am CEST time. Is it okay like that?

**Comment by winhamwr** [comment]
I think I have it successfully transferred ownership and removed myself from Avocode. Does everything look good from your end? 

I'd also love push access to this repo as an outside contributor, if you don't mind.

**Comment by petrbrzek** [comment]
@winhamwr Awesome, thanks a lot. I've added you as a collaborator.

**Comment by petrbrzek** [comment]
I'm closing the issue now as we transferred repo under Avocode organisation.
