### ISSUE TITLE
add in a CmdOrCtrl/CommandOrControl Key

### ISSUE THREAD

**Issue by Kilian** [avocode/combokeys#53]
Electron Accelerators have a special key called "CtrlOrCmd" that will intelligently choose whether to use one or the other, depending on platform: https://github.com/electron/electron/blob/master/docs/api/accelerator.md#platform-notice

It think this would be great for combokeys too. Here is some code to achieve this using combokeys in Electron (for a more generic option, swap out out the ternary statement for something checking navigator.platform)

```
const CmdOrCtrl = process.platform === 'darwin' ? 'command' : 'ctrl';
combokeys.bind([`${CmdOrCtrl}+S`], function(e) {
    _saveDraft();
    return false;
});
```
But I would prefer to just write:
```
combokeys.bind([`CmdOrCtrl+S`], function(e) {
    _saveDraft();
    return false;
});
```
I think it would make a pleasant improvement to this nice library :)

**Comment by petrbrzek** [comment]
Hey, and sorry for the very late response. Combokeys already has alias for handling this case.
See here https://github.com/avocode/combokeys/blob/4535f786039a6cdd04bb2d7d6813b77fada763f4/helpers/special-aliases.js#L14.

Is it what you wanted right?

**Comment by Kilian** [comment]
Yeah, nice! I like the 'CmdOrCtrl' naming of electron but this works as well :)
